### ISSUE TITLE
Dependency Mingw32

### ISSUE THREAD

**Issue by d0ubl3puls4r** [M4sc3r4n0/avoidz#1]
Hello, I am using Kali 2017.1, and I am not able to install the Mingw32 dependency. How to install dependency in order to use avoidz

**Comment by M4sc3r4n0** [comment]
here the solution
leafpad /etc/apt/sources.list
add this line : deb http://old.kali.org/kali sana main non-free contrib
save
and run setup.sh
after installing mingw32 remove : deb http://old.kali.org/kali sana main non-free contrib 
from sources.list

**Comment by d0ubl3puls4r** [comment]
Thank you, I was able to install the mingw32
